export default {

    // GET ALL EVENTS (FOR LIST)
    EVENTS_LOADING: "EVENTS_LOADING",
    EVENTS_LOADED: "EVENTS_LOADED",
    EVENTS_LOADING_ERROR: "EVENTS_LOADING_ERROR",

    // GET AN EVENT (FOR DETAILS)
    EVENT_LOADING: "EVENT_LOADING",
    EVENT_LOADED: "EVENT_LOADED",
    EVENT_LOADING_ERROR: "EVENT_LOADING_ERROR",

    // CREATE AN EVENT
    EVENT_CREATING: "EVENT_CREATING",
    EVENT_CREATED: "EVENT_CREATED",
    EVENT_CREATE_ERROR: "EVENT_CREATE_ERROR",

    // UPDATE AN EVENT
    EVENT_UPDATNG: "EVENT_UPDATING",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_UPDATE_ERROR: "EVENT_UPDATE_ERROR",

    // DELETE AN EVENT
    EVENT_DELETING: "EVENT_DELETING",
    EVENT_DELETED: "EVENT_DELETED",
    EVENT_DELETE_ERROR: "EVENT_DELETE_ERROR",

    //CHECK TEAM
    CHECKING_TEAM: "CHECKING_TEAM",
    TEAM_CHECKED: "TEAM_CHECKED",
    TEAM_CHECK_ERROR: "TEAM_CHECK_ERROR",

    // BUIlD TEAM
    TEAM_BUILDING: "TEAM_BUILDING",
    TEAM_BUILT: "TEAM_BUILT",
    TEAM_BUILD_ERROR: "TEAM_BUILD_ERROR",

    // CLOSE EVENT
    CLOSING_EVENT: "CLOSING_EVENT",
    EVENT_CLOSED: "EVENT_CLOSED",
    EVENT_CLOSE_ERROR: "EVENT_CLOSE_ERROR",

    //ASSIGN SCOUT
    ASSIGNING_SCOUT: "ASSIGNING_SCOUT",
    SCOUT_ASSIGNED: "SCOUT_ASSIGNED",
    SCOUT_ASSIGN_ERROR: "SCOUT_ASSIGN_ERROR",

    // FIND AN EVENT
    EVENT_SEARCHING: "EVENT_SEARCHING",
    EVENT_SEARCH_FOUND: "EVENT_SEARCH_FOUND",
    EVENT_SEARCH_NOTFOUND: "EVENT_SEARCH_NOTFOUND",
    EVENT_SEARCH_ERROR: "EVENT_SEARCH_ERROR",
}